#ifndef futura_weather_redux_config_h
#define futura_weather_redux_config_h

enum AppMessageKey {
	REQUEST_WEATHER_MSG_KEY = 1,
	SET_WEATHER_MSG_KEY = 2,
    WEATHER_TEMPERATURE_MSG_KEY = 3,
    WEATHER_CONDITIONS_MSG_KEY = 4,
	SET_PREFERENCES_MSG_KEY = 5,
	TEMP_FORMAT_MSG_KEY = 6,
	WEATHER_UPDATE_FREQ_MSG_KEY = 7,
	STATUSBAR_MSG_KEY = 8,
	WEATHER_OUTDATED_TIME_MSG_KEY = 9
};

enum PersistKey {
	PREF_TEMP_FORMAT_PERSIST_KEY = 1,
	PREF_WEATHER_UPDATE_FREQ_PERSIST_KEY = 2,
	PREF_STATUSBAR_PERSIST_KEY = 3,
	PREF_WEATHER_OUTDATED_TIME_PERSIST_KEY = 4,
	WEATHER_CACHE_LAST_UPDATE_PERSIST_KEY = 5,
	WEATHER_CACHE_TEMPERATURE_PERSIST_KEY = 6,
	WEATHER_CACHE_CONDITIONS_PERSIST_KEY = 7
};

typedef enum {
	TEMP_FORMAT_CELCIUS = 1,
	TEMP_FORMAT_FAHRENHEIT = 2
} TempFormat;

#endif
