#ifndef futura_weather_redux_config_h
#define futura_weather_redux_config_h

enum AppMessageKey {
	REQUEST_WEATHER_MSG_KEY         = 1,
	SET_WEATHER_MSG_KEY             = 2,
    WEATHER_TEMPERATURE_MSG_KEY     = 3,
    WEATHER_CONDITION_CODE_MSG_KEY  = 4,
	WEATHER_CONDITION_FLAGS_MSG_KEY = 5,
	SET_PREFERENCES_MSG_KEY         = 6,
	TEMP_FORMAT_MSG_KEY             = 7,
	WEATHER_UPDATE_FREQ_MSG_KEY     = 8,
	STATUSBAR_MSG_KEY               = 9,
	WEATHER_OUTDATED_TIME_MSG_KEY   = 10,
	WEATHER_PROVIDER_MSG_KEY        = 11,
	LANGUAGE_CODE_MSG_KEY           = 12,
	TRANSLATION_MSG_KEY             = 13
};

enum PersistKey {
	PREF_TEMP_FORMAT_PERSIST_KEY = 1,
	PREF_WEATHER_UPDATE_FREQ_PERSIST_KEY = 2,
	PREF_STATUSBAR_PERSIST_KEY = 3,
	PREF_WEATHER_OUTDATED_TIME_PERSIST_KEY = 4,
	PREF_WEATHER_PROVIDER_PERSIST_KEY = 5,
	PREF_LANGUAGE_CODE_PERSIST_KEY = 6,
	PREF_TRANSLATION_PERSIST_KEY = 7,
	WEATHER_CACHE_LAST_UPDATE_PERSIST_KEY = 8,
	WEATHER_CACHE_TEMPERATURE_PERSIST_KEY = 9,
	WEATHER_CACHE_CONDITION_CODE_PERSIST_KEY = 10,
	WEATHER_CACHE_CONDITION_FLAGS_PERSIST_KEY = 11
};

typedef enum {
	TEMP_FORMAT_CELCIUS = 1,
	TEMP_FORMAT_FAHRENHEIT = 2
} TempFormat;

#endif
